# Generated by Django 4.1.1 on 2022-09-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
